---
deployment:
  tasks:
    - export DEPLOYPATH=/home/customar/dragonbiketours.com
    - export DEPLOYPATH2=/home/customar/dragonbiketours.com/assets
    - rsync -a -v --delete-after /home/customar/repositories/dragon-bikes/index.html $DEPLOYPATH
    - rsync -a -v --delete-after /home/customar/repositories/dragon-bikes/assets/ $DEPLOYPATH2
