---
deployment:
  tasks:
    - export DEPLOYPATH=/home/customar/saigonbikerentals.com
    - export DEPLOYPATH2=/home/customar/saigonbikerentals.com/assets
    - rsync -a -v --delete-after /home/customar/repositories/saigonbikerentals-public/index.html $DEPLOYPATH
    - rsync -a -v --delete-after /home/customar/repositories/saigonbikerentals-public/assets/ $DEPLOYPATH2
